version: 2

models:
  - name: stg_greenery_addresses
    description: "addresses 1st model"

  - name: stg_greenery_events
    description: "events 1st model"

  - name: stg_greenery_order_items
    description: "order_items 1st model"

  - name: stg_greenery_orders
    description: "orders 1st model"

  - name: stg_greenery_products
    description: "products 1st model"

  - name: stg_greenery_promos
    description: "promos 1st model"

  - name: stg_greenery_users
    description: "users 1rst model"
